project_id = "uzhaicqvntxcsxmkyobk"

[functions.stripe-webhook]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.track-usage]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.generate-image]
verify_jwt = false

[functions.edit-image]
verify_jwt = false